spring:
  application:
    name: SPRINGBOOTRESTENDTOENDAPPLICATION
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    url: jdbc:mysql://database-1.cro0q6igmpws.ap-south-2.rds.amazonaws.com:3306/srinuawstest?useSSL=false&allowPublicKeyRetrieval=true
    password: ${MYSQL_PASSWORD:mysqlroot}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: srinuvasrao966@gmail.com
    password: tccl vnxy jwsv ayhf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
logging:
  file:
    name: C:/Users/Welcome/Desktop/logs/springbootbackendelk.log

management:
  tracing:
    sampling:
      probability: 1.0